before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: hDCTHnSXECG50wn7HjZ5sntAoMIbTE1OUcBCRGJf7blfZluFEuIFJs+6B3AvTqZi68NBcj5pZJVOPyeeqx7J/7w84YjPdYpCStsCYedTW1F+E4pWqTTxcoJr1mYIp/qpNEF43Dy2SnGv0K4js5DJaYMH6RTmA4Zrsgos9FLDfWFFV4tqhA27570F61IofjmVyj/bicJAtARt8Axf3YT53gMHRIk/autliAnf36WeGLd2CR/6/ntMFDYHv7w/Pqm1VGaPCQvIr2P1A8F4PQqbn+CQ1BDZ0yVXhXm2pfd2DnFHMRdLumxERR+7faZ8HFQ5MMJ7EmlQ/N2OWtGfRNCPhR5nlxFi0DEovoh+yJuL2GQyL143ZKCIeLSPHujj2nLD4m33NDU77FJCv7XCXEtudMY1mQZZITIKM7+Z6CEgJ91yMOmEYVg1zZc5jSwIOZCTl7UqPG8gJ//pQIOvNM/xyfmYiQtiHjjcv45yWEVMcrYEXQkEJW5qlZIP0GqMVa+KKMKQqrQYbCQuX0n9lcnXpEzrnKbdPlIXViQXb3EGPioTMbzuzjJuyH9iPgpEM1nLE0wraHegUceQ7Fk70PwhK7LB4ihLWAKy/fk4kzpM8bzFXHhm0qXFdtpgvO9vkJrWSV12m8ukVKKmmO3xG+N3htgn+aKI+5xygtr5lChDpHU= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
